### ISSUE TITLE
Translator: sometimes string array is not supported

### ISSUE THREAD

**Issue by Hardenn** [RedMadRobot/DAO-generator#2]
One model with `var emailListValue: [String]?` is generated into `entity.emailListValue = fromEntry.emailListValue.map { $0.value }`

But other with `var values: [String]` is generated into `FIX ME`.

**Comment by vani2** [comment]
Fixed in https://github.com/RedMadRobot/DAO-generator/commit/3960713acc26b9e5cf232d62cf6dbc34ea6de9d6
